#!/usr/bin/env ruby

require './hb_writer'

USAGE = './hw <entry>'

if ARGV.size != 1
  warn USAGE
  exit
end

writer = HBWriter.new
open(ARGV[0], 'r+') do |f|
  entry = writer.post_entry(f.read)
  f.seek(0, IO::SEEK_SET)
  f.write(entry)
end
